#!/bin/bash -eu

cmd_path=`which nippo`
current_path=${cmd_path%nippo}
config_file=${current_path}nippo.conf

echo "nippo start"

echo "read config..."
config_text=`sed -e 's/:[^:\/\/]/="/g;s/$/"/g;s/ *=/=/g' ${config_file}`
config=(`echo ${config_text}`)
for c in ${config[@]}
do
  eval ${c}
done

if [ $# -eq 0 ]
then
  echo "にっぽにっぽにっぽ"
  exit 0
fi

case $1 in
  config)
    cat ${config_file}
    echo ""
    ;;
  *)
    echo "ちゃうねん"
    ;;
esac