#!/bin/bash -eu

### font ###
ALERT="\e[1;31m"
NORMAL="\e[m"

### config ###
cmd_path=`which nippo`
current_path=${cmd_path%nippo}
config_file=${current_path}nippo.conf

echo "[nippo]"

printf "read config"
config_text=`sed -e 's/:[^:\/\/]/="/g;s/$/"/g;s/ *=/=/g' ${config_file}`
config=(`echo ${config_text}`)
for c in ${config[@]}
do
  eval ${c}
  printf '.'
done
printf "\n"

### functions ###

make()
{
  cd ${nippo_dir}
  mkdir -p `date +${dir_format}`
  touch `date +${dir_format}`/${filename_format}

  ### -o text_editor
}

open()
{
  case $# in
    0)
      dir=${nippo_dir}/`date +${dir_format}`/${filename_format}
      ;;
    1)
      case $1 in
        -d)
          dir=${nippo_dir}
          ;;
        *)
        printf "${ALERT}wrong arguments!${NORMAL}\n"
        exit 1
        ;;
      esac
      ;;
  esac

  eval "${text_editor} ${dir}"
}

push()
{
  echo "push(pending)"
}

### process request ###
if [ $# -eq 0 ]
then
  echo "にっぽにっぽにっぽ"
  exit 0
fi

### 1:$# 2:許容する引数の数 ###
check_arg_num()
{
  if [ $1 -gt $2 ]
  then
    printf "${ALERT}wrong number of arguments!${NORMAL}\n"
    exit 1
  fi
}

case $1 in
  make)
    check_arg_num $# 2
    make ${*/make}
    ;;
  open)
    check_arg_num $# 2
    open ${*/open}
    ;;
  push)
    check_arg_num $# 2
    push ${*/push}
    ;;
  config)
    cat ${config_file}
    echo ""
    ;;
  *)
    echo "ちゃうねん"
    ;;
esac